/*! deckforge | MIT License | https://github.com/lrivallain/deckforge */
(()=>{(function(){"use strict";let u=document.documentElement,r=Array.from(document.querySelectorAll(".stage > .slide")),f=document.querySelector(".controls");if(!r.length||!f)return;let d=e=>document.getElementById(e),y=d("df-previous"),x=d("df-next"),p=d("df-slide-select"),v=d("df-static"),w=d("df-notes"),P=d("df-presenter"),b=d("df-fullscreen"),m=d("df-announcement"),c=C(),o=0,s=null,E=null,l=null;function C(){let e=document.querySelector('meta[name="deckforge-editor"]'),t=e&&e.getAttribute("content");if(!t||!/^\/(?!\/)/.test(t))return null;let n=document.createElement("a");return n.id="df-edit",n.href=t,n.title="Edit this slide (E)",n.textContent="Edit",n.dataset.base=t,f.insertBefore(n,m),n}let D=parseFloat(getComputedStyle(u).getPropertyValue("--df-motion-stagger"))||.15;for(let e of r){let t=0;for(let n of e.querySelectorAll(".reveal")){let i=n.getAttribute("data-df-order"),M=i!==null&&/^\d+$/.test(i)?Number(i):t++;n.style.getPropertyValue("--delay")||n.style.setProperty("--delay",`${(M*D).toFixed(2)}s`)}}r.forEach((e,t)=>{let n=document.createElement("option");n.value=String(t),n.textContent=`${t+1} / ${r.length} - ${e.dataset.title||"Slide"}`,p.append(n)});function k(){let e=/^#([1-9]\d*)$/.exec(location.hash);if(e){let n=Number(e[1]);return Number.isSafeInteger(n)&&n<=r.length?n-1:0}let t=/^#slide-([\w-]+)$/.exec(location.hash);if(t){let n=r.findIndex(i=>i.dataset.slideId===t[1]);if(n>=0)return n}return 0}function L(e){let t=r[e]&&r[e].querySelector(".slide-notes");return t?t.innerHTML:""}function S(){if(!l)return;let e=L(o);l.innerHTML=e||'<p class="empty">No speaker notes for this slide.</p>'}function g(e){if(e)for(let t of e.querySelectorAll('img[loading="lazy"]'))t.loading="eager"}function h(){r.forEach(g)}if(document.readyState==="complete"?setTimeout(h,200):addEventListener("load",()=>setTimeout(h,200)),addEventListener("beforeprint",h),window.matchMedia){let e=window.matchMedia("print");e.addEventListener&&e.addEventListener("change",t=>t.matches&&h())}function a(e){if(o=Math.max(0,Math.min(r.length-1,e)),g(r[o]),g(r[o+1]),g(r[o-1]),r.forEach((t,n)=>{t.hidden=n!==o,t.classList.remove("entered")}),r[o].offsetWidth,r[o].classList.add("entered"),y.disabled=o===0,x.disabled=o===r.length-1,p.value=String(o),m.textContent=`Slide ${o+1} of ${r.length}: ${r[o].dataset.title||""}`,location.hash!==`#${o+1}`&&history.replaceState(null,"",`#${o+1}`),c){let t=r[o].dataset.slideId;c.href=t?`${c.dataset.base.split("#")[0]}#slide-${t}`:c.dataset.base}S(),F()}function $(){let e=u.classList.toggle("static");v.setAttribute("aria-pressed",String(e))}function A(){let e=u.classList.toggle("show-notes");w.setAttribute("aria-pressed",String(e)),e?(l=document.createElement("section"),l.className="notes-panel",l.setAttribute("aria-label","Speaker notes"),f.before(l),S()):l&&(l.remove(),l=null)}let q=`
    body{margin:0;font:16px/1.5 system-ui,sans-serif;color:#16202F;background:#F7F9FC;display:grid;grid-template-rows:auto 1fr auto;height:100vh}
    header,footer{display:flex;gap:12px;align-items:center;justify-content:space-between;padding:12px 20px;background:#fff;border-bottom:1px solid #E2E8F2}
    footer{border-top:1px solid #E2E8F2;border-bottom:0}
    h1{font-size:20px;margin:0}
    .meta{color:#53617A;font-variant-numeric:tabular-nums}
    main{overflow:auto;padding:20px 24px;font-size:22px;line-height:1.5}
    main p{margin:0 0 .7em}
    .empty{color:#53617A;font-style:italic}
    button{font:inherit;min-height:40px;padding:6px 14px;border:1px solid #53617A;border-radius:7px;background:#fff;cursor:pointer}
    button:disabled{color:#53617A;border-color:#E2E8F2;cursor:default}
    :focus-visible{outline:3px solid #0F6CBD;outline-offset:3px}`;function F(){if(!s||s.closed)return;let e=s.document,t=e.getElementById("p-title");t&&(t.textContent=`${o+1} / ${r.length} \u2014 ${r[o].dataset.title||""}`,e.getElementById("p-notes").innerHTML=L(o)||'<p class="empty">No speaker notes for this slide.</p>',e.getElementById("p-next").textContent=o<r.length-1?`Next: ${r[o+1].dataset.title||""}`:"End of deck",e.getElementById("p-prev-btn").disabled=o===0,e.getElementById("p-next-btn").disabled=o===r.length-1)}function B(){if(s&&!s.closed){s.focus();return}if(s=window.open("","deckforge-presenter","popup,width=960,height=640"),!s){m.textContent="The presenter window was blocked. Allow pop-ups for this page, or use Notes.";return}E=E||Date.now();let e=s.document;e.open(),e.write(`<!doctype html><html lang="${u.lang||"en"}"><head><meta charset="utf-8"><title>Presenter \u2014 ${document.title.replace(/</g,"&lt;")}</title><style>${q}</style></head><body>
      <header><h1 id="p-title" aria-live="polite"></h1><span class="meta" id="p-clock"></span></header>
      <main id="p-notes" aria-label="Speaker notes"></main>
      <footer><span class="meta" id="p-next"></span><span><button id="p-prev-btn" type="button">Previous</button> <button id="p-next-btn" type="button">Next</button></span></footer>
    </body></html>`),e.close(),e.getElementById("p-prev-btn").addEventListener("click",()=>a(o-1)),e.getElementById("p-next-btn").addEventListener("click",()=>a(o+1)),e.addEventListener("keydown",N);let t=()=>{if(!s||s.closed)return;let n=Math.floor((Date.now()-E)/1e3),i=e.getElementById("p-clock");i&&(i.textContent=`Elapsed ${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`),s.setTimeout(t,1e3)};t(),F()}async function I(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else throw new Error("unsupported")}catch{m.textContent="Fullscreen is not available in this browser or was denied."}}document.addEventListener("fullscreenchange",()=>{b.setAttribute("aria-pressed",String(!!document.fullscreenElement))});function N(e){if(e.defaultPrevented||e.ctrlKey||e.metaKey||e.altKey||e.shiftKey)return;let t=e.target;if(t&&typeof t.closest=="function"){let i=t.ownerDocument!==document?"input, select, textarea, [contenteditable]":"a, button, input, select, textarea, [contenteditable]";if(t.closest(i))return}let n;switch(e.key){case"ArrowRight":case"PageDown":case" ":n=o+1;break;case"ArrowLeft":case"PageUp":n=o-1;break;case"Home":n=0;break;case"End":n=r.length-1;break;case"s":case"S":e.preventDefault(),$();return;case"n":case"N":e.preventDefault(),A();return;case"p":case"P":e.preventDefault(),B();return;case"f":case"F":e.preventDefault(),I();return;case"e":case"E":if(!c)return;e.preventDefault(),location.href=c.href;return;default:return}e.preventDefault(),a(n)}y.addEventListener("click",()=>a(o-1)),x.addEventListener("click",()=>a(o+1)),p.addEventListener("change",()=>a(Number(p.value))),v.addEventListener("click",$),w.addEventListener("click",A),P.addEventListener("click",B),b.addEventListener("click",I),document.documentElement.requestFullscreen||(b.hidden=!0),addEventListener("hashchange",()=>a(k())),addEventListener("keydown",N),addEventListener("beforeprint",()=>r.forEach(e=>e.classList.add("entered"))),addEventListener("pagehide",()=>{s&&!s.closed&&s.close()}),window.deckforge={go:e=>a(e),next:()=>a(o+1),previous:()=>a(o-1),get current(){return o},get count(){return r.length}},u.classList.add("presenting"),f.hidden=!1,a(k())})();})();
