/*! deckforge | MIT License | https://github.com/lrivallain/deckforge */
(()=>{(function(){"use strict";let d=document.documentElement,r=Array.from(document.querySelectorAll(".stage > .slide")),p=document.querySelector(".controls");if(!r.length||!p)return;let i=e=>document.getElementById(e),h=i("df-previous"),b=i("df-next"),u=i("df-slide-select"),y=i("df-static"),E=i("df-notes"),B=i("df-presenter"),f=i("df-fullscreen"),m=i("df-announcement"),t=0,s=null,g=null,l=null,P=parseFloat(getComputedStyle(d).getPropertyValue("--df-motion-stagger"))||.15;for(let e of r){let n=0;for(let o of e.querySelectorAll(".reveal"))o.style.getPropertyValue("--delay")||o.style.setProperty("--delay",`${(n*P).toFixed(2)}s`),n++}r.forEach((e,n)=>{let o=document.createElement("option");o.value=String(n),o.textContent=`${n+1} / ${r.length} - ${e.dataset.title||"Slide"}`,u.append(o)});function x(){let e=/^#([1-9]\d*)$/.exec(location.hash);if(e){let o=Number(e[1]);return Number.isSafeInteger(o)&&o<=r.length?o-1:0}let n=/^#slide-([\w-]+)$/.exec(location.hash);if(n){let o=r.findIndex(c=>c.dataset.slideId===n[1]);if(o>=0)return o}return 0}function v(e){let n=r[e]&&r[e].querySelector(".slide-notes");return n?n.innerHTML:""}function w(){if(!l)return;let e=v(t);l.innerHTML=e||'<p class="empty">No speaker notes for this slide.</p>'}function a(e){t=Math.max(0,Math.min(r.length-1,e)),r.forEach((n,o)=>{n.hidden=o!==t,n.classList.remove("entered")}),r[t].offsetWidth,r[t].classList.add("entered"),h.disabled=t===0,b.disabled=t===r.length-1,u.value=String(t),m.textContent=`Slide ${t+1} of ${r.length}: ${r[t].dataset.title||""}`,location.hash!==`#${t+1}`&&history.replaceState(null,"",`#${t+1}`),w(),S()}function k(){let e=d.classList.toggle("static");y.setAttribute("aria-pressed",String(e))}function L(){let e=d.classList.toggle("show-notes");E.setAttribute("aria-pressed",String(e)),e?(l=document.createElement("section"),l.className="notes-panel",l.setAttribute("aria-label","Speaker notes"),p.before(l),w()):l&&(l.remove(),l=null)}let I=`
    body{margin:0;font:16px/1.5 system-ui,sans-serif;color:#16202F;background:#F7F9FC;display:grid;grid-template-rows:auto 1fr auto;height:100vh}
    header,footer{display:flex;gap:12px;align-items:center;justify-content:space-between;padding:12px 20px;background:#fff;border-bottom:1px solid #E2E8F2}
    footer{border-top:1px solid #E2E8F2;border-bottom:0}
    h1{font-size:20px;margin:0}
    .meta{color:#53617A;font-variant-numeric:tabular-nums}
    main{overflow:auto;padding:20px 24px;font-size:22px;line-height:1.5}
    main p{margin:0 0 .7em}
    .empty{color:#53617A;font-style:italic}
    button{font:inherit;min-height:40px;padding:6px 14px;border:1px solid #53617A;border-radius:7px;background:#fff;cursor:pointer}
    button:disabled{color:#53617A;border-color:#E2E8F2;cursor:default}
    :focus-visible{outline:3px solid #0F6CBD;outline-offset:3px}`;function S(){if(!s||s.closed)return;let e=s.document,n=e.getElementById("p-title");n&&(n.textContent=`${t+1} / ${r.length} \u2014 ${r[t].dataset.title||""}`,e.getElementById("p-notes").innerHTML=v(t)||'<p class="empty">No speaker notes for this slide.</p>',e.getElementById("p-next").textContent=t<r.length-1?`Next: ${r[t+1].dataset.title||""}`:"End of deck",e.getElementById("p-prev-btn").disabled=t===0,e.getElementById("p-next-btn").disabled=t===r.length-1)}function $(){if(s&&!s.closed){s.focus();return}if(s=window.open("","deckforge-presenter","popup,width=960,height=640"),!s){m.textContent="The presenter window was blocked. Allow pop-ups for this page, or use Notes.";return}g=g||Date.now();let e=s.document;e.open(),e.write(`<!doctype html><html lang="${d.lang||"en"}"><head><meta charset="utf-8"><title>Presenter \u2014 ${document.title.replace(/</g,"&lt;")}</title><style>${I}</style></head><body>
      <header><h1 id="p-title" aria-live="polite"></h1><span class="meta" id="p-clock"></span></header>
      <main id="p-notes" aria-label="Speaker notes"></main>
      <footer><span class="meta" id="p-next"></span><span><button id="p-prev-btn" type="button">Previous</button> <button id="p-next-btn" type="button">Next</button></span></footer>
    </body></html>`),e.close(),e.getElementById("p-prev-btn").addEventListener("click",()=>a(t-1)),e.getElementById("p-next-btn").addEventListener("click",()=>a(t+1)),e.addEventListener("keydown",A);let n=()=>{if(!s||s.closed)return;let o=Math.floor((Date.now()-g)/1e3),c=e.getElementById("p-clock");c&&(c.textContent=`Elapsed ${String(Math.floor(o/60)).padStart(2,"0")}:${String(o%60).padStart(2,"0")}`),s.setTimeout(n,1e3)};n(),S()}async function F(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else throw new Error("unsupported")}catch{m.textContent="Fullscreen is not available in this browser or was denied."}}document.addEventListener("fullscreenchange",()=>{f.setAttribute("aria-pressed",String(!!document.fullscreenElement))});function A(e){if(e.defaultPrevented||e.ctrlKey||e.metaKey||e.altKey||e.shiftKey)return;let n=e.target;if(n&&typeof n.closest=="function"){let c=n.ownerDocument!==document?"input, select, textarea, [contenteditable]":"a, button, input, select, textarea, [contenteditable]";if(n.closest(c))return}let o;switch(e.key){case"ArrowRight":case"PageDown":case" ":o=t+1;break;case"ArrowLeft":case"PageUp":o=t-1;break;case"Home":o=0;break;case"End":o=r.length-1;break;case"s":case"S":e.preventDefault(),k();return;case"n":case"N":e.preventDefault(),L();return;case"p":case"P":e.preventDefault(),$();return;case"f":case"F":e.preventDefault(),F();return;default:return}e.preventDefault(),a(o)}h.addEventListener("click",()=>a(t-1)),b.addEventListener("click",()=>a(t+1)),u.addEventListener("change",()=>a(Number(u.value))),y.addEventListener("click",k),E.addEventListener("click",L),B.addEventListener("click",$),f.addEventListener("click",F),document.documentElement.requestFullscreen||(f.hidden=!0),addEventListener("hashchange",()=>a(x())),addEventListener("keydown",A),addEventListener("beforeprint",()=>r.forEach(e=>e.classList.add("entered"))),addEventListener("pagehide",()=>{s&&!s.closed&&s.close()}),window.deckforge={go:e=>a(e),next:()=>a(t+1),previous:()=>a(t-1),get current(){return t},get count(){return r.length}},d.classList.add("presenting"),p.hidden=!1,a(x())})();})();
