// Development preview: rebuild dist/ on change and run `deckforge edit` (or
// `deckforge serve` with --serve) on a scratch copy of the example deck,
// restarting the server when src/, bin/ or dist/ change.
//
// Usage: node scripts/dev.js [--port N] [--reset] [--serve]
//   --port N  force a port (default: first free port in 4370-4399, picked once
//             at startup so restarts keep the same URL)
//   --reset   restore .demo/preview from examples/starter before starting
//   --serve   run the read-only viewer (`deckforge serve`) instead of the editor
//
// Several worktrees can run this at the same time: each one reserves its port
// with a lock file in the OS temp dir, and keeps its own token in
// .demo/preview-token.

import { spawn } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PORT_RANGE = [4370, 4399];
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const example = path.join(root, "examples", "starter");
const work = path.join(root, ".demo", "preview");
const tokenFile = path.join(root, ".demo", "preview-token");
const lockDir = path.join(os.tmpdir(), "deckforge-dev-ports");
// Build outputs regenerated by the server; not copied from the example.
const GENERATED = new Set(["deck.html", "deckforge"]);

const argv = process.argv.slice(2);
const flag = (name) => argv.includes(name);
const portIndex = argv.indexOf("--port");
const forcedPort = portIndex > -1 ? Number(argv[portIndex + 1]) : null;
if (forcedPort !== null && !(Number.isInteger(forcedPort) && forcedPort > 0 && forcedPort < 65536)) {
  console.error("dev: --port must be an integer between 1 and 65535");
  process.exit(1);
}
const mode = flag("--serve") ? "serve" : "edit";

function restoreExample() {
  fs.rmSync(work, { recursive: true, force: true });
  fs.mkdirSync(work, { recursive: true });
  for (const entry of fs.readdirSync(example)) {
    if (GENERATED.has(entry)) continue;
    fs.cpSync(path.join(example, entry), path.join(work, entry), { recursive: true });
  }
}

/** True when something already accepts connections on host:port. */
function accepts(port, host) {
  return new Promise((resolve) => {
    const socket = net.connect({ port, host });
    const done = (result) => {
      socket.destroy();
      resolve(result);
    };
    socket.setTimeout(300, () => done(false));
    socket.once("connect", () => done(true));
    socket.once("error", () => done(false));
  });
}

/** True when the server could bind 127.0.0.1:port right now. */
function canBind(port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once("error", () => resolve(false));
    server.listen(port, "127.0.0.1", () => server.close(() => resolve(true)));
  });
}

async function isFree(port) {
  // A connect probe catches wildcard (0.0.0.0 / ::) listeners that macOS still
  // lets us bind over on 127.0.0.1.
  if ((await accepts(port, "127.0.0.1")) || (await accepts(port, "::1"))) return false;
  return canBind(port);
}

const alive = (pid) => {
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    return err.code === "EPERM";
  }
};

let lockFile = null;
/** Reserve a port against other dev.js instances (atomic create, stale locks reclaimed). */
function tryLock(port) {
  fs.mkdirSync(lockDir, { recursive: true });
  const file = path.join(lockDir, `${port}.lock`);
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      fs.writeFileSync(file, String(process.pid), { flag: "wx" });
      lockFile = file;
      return true;
    } catch (err) {
      if (err.code !== "EEXIST") throw err;
      const owner = Number(fs.readFileSync(file, "utf8"));
      if (owner && alive(owner)) return false;
      fs.rmSync(file, { force: true });
    }
  }
  return false;
}
const unlock = () => {
  if (lockFile) fs.rmSync(lockFile, { force: true });
  lockFile = null;
};

async function pickPort() {
  if (forcedPort !== null) {
    if (!(await isFree(forcedPort))) {
      console.error(`dev: port ${forcedPort} is already in use`);
      process.exit(1);
    }
    return forcedPort;
  }
  for (let port = PORT_RANGE[0]; port <= PORT_RANGE[1]; port++) {
    if (!tryLock(port)) continue;
    if (await isFree(port)) return port;
    unlock();
  }
  // Whole range busy: let the OS pick one, then keep it for the session.
  const server = net.createServer();
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address();
  await new Promise((resolve) => server.close(resolve));
  return port;
}

if (flag("--reset")) {
  restoreExample();
  console.log("dev: restored .demo/preview from examples/starter");
} else if (!fs.existsSync(path.join(work, "deck.yaml"))) {
  restoreExample();
}
if (!fs.existsSync(tokenFile)) fs.writeFileSync(tokenFile, crypto.randomBytes(12).toString("base64url"));
const token = fs.readFileSync(tokenFile, "utf8").trim();
const port = await pickPort();
// Keep port numbers out of everything printed before the "Editor:" line: the
// GitHub Copilot app treats "port N" as a server URL and would open it without
// the token.
console.log(`dev: deckforge ${mode} on ${path.relative(root, work)}/deck.yaml (same URL across restarts)`);

const children = new Set();
let stopping = false;
const run = (args, env = {}) => {
  const child = spawn(process.execPath, args, { cwd: root, stdio: "inherit", env: { ...process.env, CI: "", ...env } });
  children.add(child);
  child.once("exit", (code, signal) => {
    children.delete(child);
    if (!stopping) {
      console.error(`dev: ${args.join(" ")} exited (${signal || code}); stopping`);
      stop(1);
    }
  });
  return child;
};

function stop(code = 0) {
  if (stopping) return;
  stopping = true;
  for (const child of children) child.kill("SIGTERM");
  const force = setTimeout(() => {
    for (const child of children) child.kill("SIGKILL");
  }, 3000);
  const finish = () => {
    if (children.size) return;
    clearTimeout(force);
    unlock();
    process.exit(code);
  };
  for (const child of children) child.once("exit", finish);
  finish();
}
process.on("SIGINT", () => stop(0));
process.on("SIGTERM", () => stop(0));
process.on("SIGHUP", () => stop(0));
process.on("exit", unlock);

run(["scripts/build.js", "--watch"]);
// Give esbuild a moment to produce dist/ before the server starts.
setTimeout(() => {
  if (stopping) return;
  const cliArgs = [mode, path.join(work, "deck.yaml"), "--port", String(port), "--no-open"];
  if (mode === "edit") cliArgs.push("--token", token);
  run(
    ["--watch-preserve-output", "--watch-path=src", "--watch-path=bin", "--watch-path=dist", "scripts/dev-server.js"],
    { DECKFORGE_DEV_ARGS: JSON.stringify(cliArgs) },
  );
}, 800);
